spring.application.name=springboot

# H2 파일 기반 데이터베이스
# 프로젝트 실행 위치의 data 폴더에 w6.mv.db 파일 생성
spring.datasource.url=jdbc:h2:file:./data/w6
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 브라우저에서 H2 DB를 확인하기 위한 콘솔
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Entity 구조를 기준으로 테이블 생성 및 변경
spring.jpa.hibernate.ddl-auto=update

# Hibernate가 실행하는 SQL을 콘솔에 출력
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# schema.sql, data.sql은 사용하지 않음
spring.sql.init.mode=never

# JWT 적용을 위한 비밀키 코드, 만료 시간, issuer
secret-key: NiOeyFbN1Gqo10bPgUyTFsRMkJpGLXSvGP04eFqj5B30r5TcrtlSXfQ7TndvYjNvfkEKLqILn0j1SmKODO1Yw3JpBBgI3nVPEahqxeY8qbPSFGyzyEVxnl4AQcrnVneI
expiration-hours: 3
issuer: springboot-community-api
