name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/opened-docker/opened-backend
            git pull origin main

            cd ~/opened-docker/opened-frontend
            git pull origin main

            cd ~/opened-docker/opened-deploy
            docker compose down
            docker compose up -d --build